/*
=====================================================
Sales Performance & Customer Segmentation Analysis
Author: Vera Nhema Kinya
Project: Sales Performance Analytics
Description:
Business analysis queries used to evaluate sales,
customer behavior, and product performance.
=====================================================
*/


/*
-----------------------------------------------------
1. SALES BY REGION
Purpose:
Identify which geographic regions generate the most revenue
-----------------------------------------------------
*/

SELECT
    region,
    SUM(sales) AS total_sales,
    SUM(profit) AS total_profit,
    COUNT(*) AS total_orders
FROM sales
GROUP BY region
ORDER BY total_sales DESC;



/*
-----------------------------------------------------
2. SALES BY PRODUCT CATEGORY
Purpose:
Understand which product categories drive revenue
-----------------------------------------------------
*/

SELECT
    category,
    SUM(sales) AS total_sales,
    SUM(profit) AS total_profit,
    SUM(quantity) AS total_quantity
FROM sales
GROUP BY category
ORDER BY total_sales DESC;



/*
-----------------------------------------------------
3. TOP 10 PRODUCTS BY SALES
Purpose:
Identify best-selling products
-----------------------------------------------------
*/

SELECT
    product_name,
    SUM(sales) AS total_sales,
    SUM(quantity) AS total_quantity,
    SUM(profit) AS total_profit
FROM sales
GROUP BY product_name
ORDER BY total_sales DESC
LIMIT 10;



/*
-----------------------------------------------------
4. CUSTOMER LIFETIME VALUE (CLV)
Purpose:
Measure total revenue generated by each customer
-----------------------------------------------------
*/

SELECT
    customer_id,
    SUM(sales) AS lifetime_value,
    SUM(profit) AS total_profit,
    COUNT(*) AS total_orders
FROM sales
GROUP BY customer_id
ORDER BY lifetime_value DESC;



/*
-----------------------------------------------------
5. SALES PERFORMANCE BY SUB-CATEGORY
Purpose:
Identify high-performing and low-performing products
-----------------------------------------------------
*/

SELECT
    category,
    sub_category,
    SUM(sales) AS total_sales,
    SUM(profit) AS total_profit,
    SUM(quantity) AS total_quantity
FROM sales
GROUP BY category, sub_category
ORDER BY total_sales DESC;



/*
-----------------------------------------------------
6. DISCOUNT IMPACT ANALYSIS
Purpose:
Evaluate how discounts affect profitability
-----------------------------------------------------
*/

SELECT
    discount,
    COUNT(*) AS total_orders,
    SUM(sales) AS total_sales,
    SUM(profit) AS total_profit
FROM sales
GROUP BY discount
ORDER BY discount;



/*
-----------------------------------------------------
7. REGIONAL PRODUCT PERFORMANCE
Purpose:
Compare product sales across regions
-----------------------------------------------------
*/

SELECT
    region,
    category,
    SUM(sales) AS total_sales,
    SUM(profit) AS total_profit
FROM sales
GROUP BY region, category
ORDER BY region;



/*
-----------------------------------------------------
8. DATA EXPORT FOR DASHBOARDS
Purpose:
Create a clean aggregated dataset for Power BI / Excel
-----------------------------------------------------
*/

SELECT
    region,
    category,
    sub_category,
    SUM(sales) AS total_sales,
    SUM(profit) AS total_profit,
    SUM(quantity) AS total_quantity,
    AVG(discount) AS avg_discount
FROM sales
GROUP BY region, category, sub_category
ORDER BY total_sales DESC;